In [1]:
%pylab inline
from numpy.testing import *

Populating the interactive namespace from numpy and matplotlib


Write a function that given the size $n$ generates the lower triangular matrix $L$, such that:
$$
L_{ij} = i+j+1\ \quad\ \mathrm{if}\ j\leq i\mathrm{, wih}\ i = 0 \ldots n-1
$$

*Encouragement:* try to write a *one-liner* that generates the matrix. To do that focus first on the $i$-th line of the matrix. Think about it as the composition of two lists `[...]+[...]`. The first one is composed by `i+j+1` where `j` ranges from `0` to `i+1`. The second one is a list of zeros ranging from `i+1` to `n`.

In [2]:
def lower_tri_matrix(n):
    return matrix([append(arange(i+1,2*i+2), zeros(n-i-1)) for i in range(n)])
bb = lower_tri_matrix(4)
print(bb)

[[ 1.  0.  0.  0.]
 [ 2.  3.  0.  0.]
 [ 3.  4.  5.  0.]
 [ 4.  5.  6.  7.]]


In [3]:
assert_equal(type(lower_tri_matrix(3)),numpy.matrixlib.defmatrix.matrix)
assert_equal(lower_tri_matrix(5),[[1,0,0,0,0],[2,3,0,0,0],[3,4,5,0,0],[4,5,6,7,0],[5,6,7,8,9]])

Write a function that solves a lower triangular linear system:
$$
L x = b
$$
Reminder:
$$
x_i = \frac{1}{L_{ii}}\left(b_i - \sum_{j=0}^{i-1} L_{ij}\, x_j\right)
$$

In [4]:
def forward_substitutions(L,b):
    x = zeros(len(b))
    for i in range(len(b)):
        x[i] = (b[i] - einsum('ij,j', L, x)[i]) / L[i, i]
    return x

In [5]:
L = lower_tri_matrix(5)
b = ones(5)
assert_almost_equal(forward_substitutions(L,b),solve(L,b),decimal=14)

Write a function that given the size $n$ generates the upper triangular matrix $U$, such that:
$$
U_{ij} = i+j+1\ \quad\ \mathrm{if}\ j\geq i\mathrm{, wih}\ i = 0 \ldots n-1
$$

*Encouragement:* try to write a *one-liner* that generates the matrix.

In [6]:
def upper_tri_matrix(n):
    return matrix([append(zeros(i), arange(2*i+1,n + i + 1)) for i in range(n)])

In [7]:
assert_equal(upper_tri_matrix(5),[[1,2,3,4,5],[0,3,4,5,6],[0,0,5,6,7],[0,0,0,7,8],[0,0,0,0,9]])

Write a function that solves a upper triangular linear system:
$$
U x = b
$$
Reminder:
$$
x_i = \frac{1}{U_{ii}}\left(b_i - \sum_{j=i}^{n-1} U_{ij}\, x_j\right)
$$

In [8]:
def backward_substitutions(U,b):
    x = zeros(len(b))
    for i in reversed(range(len(b))):
        x[i] = (b[i] - einsum('ij,j', U, x)[i]) / U[i, i]
    return x

In [9]:
U = upper_tri_matrix(5)
b = ones(5)
assert_almost_equal(backward_substitutions(U,b),solve(U,b),decimal=14)

Write a function that performs the $LU$ factorisation of a given matrix $A$.

### Algorithm, Gaussian Elimination without pivoting, hints:
Set:
$$
U = A, \quad L = I.
$$
Choosing appropriate indexing:
$$
l_{ik} = \frac{u_{ik}}{u_{kk}}\\
u_{j,k:m} = u_{j,k:m} - l_{jk}\cdot u_{m,k:m}
$$


In [23]:
def lu_factorization(A):
    U = copy(A)
    N = A.shape[0]
    L = identity(N)
    for i in range(0, N):
        for j in range(i, N-1):
            L[j+1, i] = U[j+1, i] / U[i, i]
            U[j+1, i] = 0.
        
    #print(L)
        for k in range(i+1, N):
            for j in range(i+1, N):
                if i == 0:
                    print(U[k, j], L[k,i+1] * U[i+1, j])
                U[k, j] -= L[k,i+1] * U[i+1, j]
                if i == 0:
                    print(U)
    return L, U
                
AAA = random.rand(5,5)
#print(AAA)
L, U = lu_factorization(AAA)
print(L, U)

0.726077988198 0.726077988198
[[ 0.86855855  0.43313139  0.98389694  0.14373588  0.14797892]
 [ 0.          0.          0.22615293  0.10951776  0.51855421]
 [ 0.          0.48572642  0.90975271  0.15474786  0.04171082]
 [ 0.          0.33119027  0.2324377   0.12714624  0.83576471]
 [ 0.          0.27740425  0.06431037  0.64207041  0.09273298]]
0.22615292832 0.22615292832
[[ 0.86855855  0.43313139  0.98389694  0.14373588  0.14797892]
 [ 0.          0.          0.          0.10951776  0.51855421]
 [ 0.          0.48572642  0.90975271  0.15474786  0.04171082]
 [ 0.          0.33119027  0.2324377   0.12714624  0.83576471]
 [ 0.          0.27740425  0.06431037  0.64207041  0.09273298]]
0.109517763942 0.109517763942
[[ 0.86855855  0.43313139  0.98389694  0.14373588  0.14797892]
 [ 0.          0.          0.          0.          0.51855421]
 [ 0.          0.48572642  0.90975271  0.15474786  0.04171082]
 [ 0.          0.33119027  0.2324377   0.12714624  0.83576471]
 [ 0.          0.27740425  0

/usr/lib/python3.5/site-packages/ipykernel/__main__.py:7: RuntimeWarning: divide by zero encountered in double_scalars


In [17]:
A = random.rand(5,5)
L,U = lu_factorization(A)
assert_almost_equal(amax(A - L.dot(U)),0,decimal=14)

/usr/lib/python3.5/site-packages/ipykernel/__main__.py:7: RuntimeWarning: divide by zero encountered in double_scalars


TypeError: 'NoneType' object is not iterable

Write a function to solve the linear system $A\,x=b$, via $LU$ factorization.

In [ ]:
def lu_solve(A,b):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
A = random.rand(5,5)
b = ones((5,))
assert_almost_equal(lu_solve(A,b),solve(A,b),decimal=14)